services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: streaming-laravel-app
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
    networks:
      - streaming

  nginx:
    image: nginx:alpine
    container_name: streaming-nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - streaming

  postgres:
    image: postgres:15
    container_name: streaming-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: streaming
      POSTGRES_USER: streaming
      POSTGRES_PASSWORD: streaming
    volumes:
      - streamingdb:/var/lib/postgresql/data
    networks:
      - streaming

  redis:
    image: redis:7
    container_name: streaming-redis
    ports:
      - "6379:6379"
    networks:
      - streaming

volumes:
  streamingdb:

networks:
  streaming:
    driver: bridge
